services:
  web:
    image: ivanlanlei/my-timeopt-app:latest  #远端的image
    ports:
      - "32180:32180"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./data:/app/data  # 映射本地 data 文件夹到容器内的 /app/data
    logging:
      driver: "json-file"